# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  nixpkgs.overlays = [
    (self: super: {
      broadcom_sta = import (builtins.fetchTarball {
        url = "https://github.com/NixOS/nixpkgs/archive/310be0e.tar.gz";
        sha256 = "0l4nmks5...";  # Replace with the correct hash.
      }) { inherit system pkgs; };
    })
  ];
  nixpkgs.overlays = [
    (import ./broadcom-overlay.nix)
  ];

  boot.extraModulePackages = [ "broadcom_sta" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5a64d9bc-5366-4032-8cee-8e35ef347e67";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B92E-64CC";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/98ab2804-64e6-4a71-afec-4d9a69310470"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
