{
  imports = [
    ./bat.nix
    ./direnv.nix
    ./git.nix
    ./gpg.nix
    ./kitty.nix
    ./lf.nix
    ./mbsync.nix
    ./neomutt.nix
    ./newsboat.nix
    ./niri.nix
    ./notmuch.nix
    ./password-store.nix
    ./qutebrowser.nix
    ./ssh.nix
    ./skim.nix
    ./starship.nix
    ./swaylock.nix
    ./tmux.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
